server.port: 1000

spring:
  kafka:
    bootstrap-servers: localhost:9092

    consumer:
      group-id: quick-starters-consumer-group
      enable-auto-commit: true
#      auto-offset-reset: earliest
#      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
#      value-deserializer: org.apache.kafka.common.serialization.StringDeserializer
#      max-poll-records: 1000

    template:
      default-topic: quick-starters-log